### ISSUE TITLE
Load setting to another songs?

### ISSUE THREAD

**Issue by webwayscript** [osamabinomar/AndroidEqualizer#18]
If we change music its not work any thing i need to do?

**Comment by bullheadandplato** [comment]
You need to update `audioSessionId`

**Comment by webwayscript** [comment]
How can you share code?

**Comment by bullheadandplato** [comment]
`setAudioSessionId`
https://stackoverflow.com/questions/14373541/what-does-the-android-mediaplayer-audio-session-id-refer-to

**Comment by appsoft124** [comment]
can you share your email i want to contact you
