### ISSUE TITLE
Migrate to androidx?

### ISSUE THREAD

**Issue by iamSahdeep** [osamabinomar/AndroidEqualizer#2]

**Comment by bullheadandplato** [comment]
that will break dependent apps which are not using androidx. isn't it?

**Comment by iamSahdeep** [comment]
No, if people are not using androidx they can continue with same version they are currently using. You can mention in next release "if not using androidx use version 1.0".

**Comment by bullheadandplato** [comment]
for **AndroidX**

```gradle
dependencies {
     implementation 'com.github.mosamabinomar:AndroidEqualizer:2.0'
}
```
