### ISSUE TITLE
How do i add Dialog Equalizer with ExoPlayer.

### ISSUE THREAD

**Issue by sanojlawrence** [osamabinomar/AndroidEqualizer#21]
As per your documentation i was able to add in equalizer in activity but i was not able to open in `Dialog`. And also i want to add with `ExoPlayer` 

is there any brief documentation, to add `equalizer` with `exoplayer` and open in dialog.

Or how can we do that ?

**Comment by bullheadandplato** [comment]
https://stackoverflow.com/questions/33559318/how-can-i-get-an-audiosessionid-from-exoplayer
You need `audioSessionId` check above link to get `audioSessionId` from `ExoPlayer`
If you use version with `AndroidX` then you will have `DialogEqualizerFragment` which you can use to show equalizer in Dialog
