### ISSUE TITLE
[BUG] Equalizer stops working

### ISSUE THREAD

**Issue by godred2** [osamabinomar/AndroidEqualizer#22]
When the Equalizer Activity is off, the Equalizer stops working
How to fix it?

**Comment by bullheadandplato** [comment]
It is because equalizer is destroyed when containing activity or dialog is destroyed. For this we need to run equalizer in a `Service` . I will try to fix this issue because it is a major issue along with managing `audioSessionId`. Thanks for reporting

**Comment by godred2** [comment]
> 
> 
> It is because equalizer is destroyed when containing activity or dialog is destroyed. For this we need to run equalizer in a `Service` . I will try to fix this issue because it is a major issue along with managing `audioSessionId`. Thanks for reporting

Thanks you
