### ISSUE TITLE
Equalizar not working Android pie version

### ISSUE THREAD

**Issue by SenthilNexware** [osamabinomar/AndroidEqualizer#4]
this library is working fine in Android 8. but not in  Android 9

**Comment by YuvarajRamesh** [comment]
yeah, me too. Could someone please assist us with this regard.

**Comment by bullheadandplato** [comment]
Can you verify if  `audioSessionId`  is working?

**Comment by SenthilNexware** [comment]
Yes audioSessionId is working fine in android 9 and 8, but Equalizer not working in android 9 devices(Sounds are not changing)

**Comment by SenthilNexware** [comment]
In Android 9 device - mEqualizer.getEnabled() always returns false, even though i have manually added mEqualizer.setEnabled(true);

But it returns true in android 8 devices
please let me know , if you need any additional details required

**Comment by bullheadandplato** [comment]
I will check it now and update here.

**Comment by bullheadandplato** [comment]
https://developer.android.com/reference/kotlin/android/media/audiofx/AudioEffect#setEnabled(kotlin.Boolean)
`setEnabled` return `int` value can you check what value it returns?
_I have tested on android 9 but I am unable to produce this issue_

**Comment by SenthilNexware** [comment]
The value is -5

**Comment by bullheadandplato** [comment]
https://developer.android.com/reference/kotlin/android/media/audiofx/AudioEffect#ERROR_INVALID_OPERATION:kotlin.Int
It says you are enabling in wrong state. I think this issue is related to `mediaPlayer`

**Comment by SenthilNexware** [comment]
Which device you have tested? i have tested with samsung devices (OS:5,7,8,9). this library working only with android 8 devices

**Comment by ayoubLTS** [comment]
it worked with me in android P Nokia but don't work in android P huawei
Is there a solution?

**Comment by bullheadandplato** [comment]
if `mEqualizer.setEnabled(true)` does not return `0` then it is issue related to device which I am afraid cannot be solved.
check https://developer.android.com/reference/kotlin/android/media/audiofx/AudioEffect#setEnabled(kotlin.Boolean) for details
