### ISSUE TITLE
Does this library work with soundPool object ?

### ISSUE THREAD

**Issue by ayoubLTS** [osamabinomar/AndroidEqualizer#7]
i want to use this library with soundPool but it not work 
`int streamId = soundPool.play(soundID, volume, volume, 2, -1, rate);
DialogEqualizerFragment fragment = DialogEqualizerFragment.newBuilder()
                    .setAudioSessionId(sessionId)
                    ...
                    .build();

fragment.show(getSupportFragmentManager(), "eq");`

**Comment by bullheadandplato** [comment]
`audioSessionId` is required. If you have a way for `SoundPool` to get `audioSessionId` then it'll work
